# Generated by Django 4.0.6 on 2023-02-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('open', models.DecimalField(decimal_places=2, max_digits=5)),
                ('high', models.DecimalField(decimal_places=2, max_digits=5)),
                ('low', models.DecimalField(decimal_places=2, max_digits=5)),
                ('close', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
            ],
        ),
    ]
